---
version: '3.7'
services:
  ## MySQL Docker Compose Config
  mysql-order-service:
    container_name: mysql-order-service
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: order-service
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Kolkata
      JAVA_TOOL_OPTIONS: "-Duser.timezone=Asia/Kolkata"
    volumes:
      - ./mysql-order-service:/var/lib/mysql
    ports:
      - "3307:3306"
    restart: always
    networks:
      - s-network

  mysql-inventory-service:
    container_name: mysql-inventory-service
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: inventory-service
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Kolkata
      JAVA_TOOL_OPTIONS: "-Duser.timezone=Asia/Kolkata"
    volumes:
      - ./mysql-inventory-service:/var/lib/mysql
    ports:
      - "3308:3306"
    restart: always
    networks:
      - s-network

  ## Mongo Docker Compose Config
  mongo-product-service:
    container_name: mongo-product-service
    image: mongo:4.4.14-rc0-focal
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo-product-service:27017/product-service
      TZ: Asia/Kolkata
      JAVA_TOOL_OPTIONS: "-Duser.timezone=Asia/Kolkata"
    ports:
      - "27017:27017"
    expose:
      - "27017"
    volumes:
      - ./mongo-product-service-data:/data/db
    restart: always
    networks:
      - s-network

  ## Keycloak Config with Mysql database
  keycloak-mysql:
    container_name: keycloak-mysql
    image: mysql:5.7
    volumes:
      - ./mysql_keycloak_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
      TZ: Asia/Kolkata
      JAVA_TOOL_OPTIONS: "-Duser.timezone=Asia/Kolkata"
    networks:
      - s-network

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:18.0.0
    command: [ "start-dev", "--import-realm" ]
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      TZ: Asia/Kolkata
      JAVA_TOOL_OPTIONS: "-Duser.timezone=Asia/Kolkata"
    ports:
      - "9191:8080"
    volumes:
      - ./realms/:/opt/keycloak/data/import/
    depends_on:
      - keycloak-mysql
    networks:
      - s-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.7.7
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      TZ: Asia/Kolkata
      JAVA_TOOL_OPTIONS: "-Duser.timezone=Asia/Kolkata"
    networks:
      - s-network

  broker:
    image: confluentinc/cp-kafka:7.7.7
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      TZ: Asia/Kolkata
      JAVA_TOOL_OPTIONS: "-Duser.timezone=Asia/Kolkata"
    networks:
      - s-network

  ## Zipkin
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - s-network

  ## Eureka Server
  discovery-server:
    image: sairam8276/discovery-server:latest
    container_name: discovery-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - Asia/Kolkata
      - JAVA_TOOL_OPTIONS=-Duser.timezone=Asia/Kolkata
    depends_on:
      - zipkin
    networks:
      - s-network

  api-gateway:
    image: sairam8276/api-gateway:latest
    container_name: api-gateway
    ports:
      - "8181:8080"
    expose:
      - "8181"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY= TRACE
      - Asia/Kolkata
      - JAVA_TOOL_OPTIONS=-Duser.timezone=Asia/Kolkata
    depends_on:
      - zipkin
      - discovery-server
      - keycloak
    networks:
      - s-network

  ## Product-Service Docker Compose Config
  product-service:
    container_name: product-service
    image: sairam8276/product-service:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - Asia/Kolkata
      - JAVA_TOOL_OPTIONS=-Duser.timezone=Asia/Kolkata
    depends_on:
      - mongo-product-service
      - discovery-server
      - api-gateway
    networks:
      - s-network

  ## Order-Service Docker Compose Config
  order-service:
    container_name: order-service
    image: sairam8276/order-service:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-order-service:3306/order_service
      - Asia/Kolkata
      - JAVA_TOOL_OPTIONS=-Duser.timezone=Asia/Kolkata
    depends_on:
      - mysql-order-service
      - broker
      - zipkin
      - discovery-server
      - api-gateway
    networks:
      - s-network

  ## Inventory-Service Docker Compose Config
  inventory-service:
    container_name: inventory-service
    image: sairam8276/inventory-service:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-inventory-service:3306/inventory_service
      - Asia/Kolkata
      - JAVA_TOOL_OPTIONS=-Duser.timezone=Asia/Kolkata
    depends_on:
      - mysql-inventory-service
      - discovery-server
      - api-gateway
    networks:
      - s-network

  ## Notification-Service Docker Compose Config
  notification-service:
    container_name: notification-service
    image: sairam8276/notification-service:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - Asia/Kolkata
      - JAVA_TOOL_OPTIONS=-Duser.timezone=Asia/Kolkata
    depends_on:
      - zipkin
      - broker
      - discovery-server
      - api-gateway
    networks:
      - s-network

  ## Prometheus
  prometheus:
    image: prom/prometheus:v2.37.1
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - product-service
      - inventory-service
      - order-service
      - notification-service
    networks:
      - s-network

  grafana:
    image: grafana/grafana-oss:8.5.2
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    links:
      - prometheus:prometheus
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
      - Asia/Kolkata
      - JAVA_TOOL_OPTIONS=-Duser.timezone=Asia/Kolkata
    networks:
      - s-network

networks:
  s-network:
    driver: bridge
